### ISSUE TITLE
Investigate how to deal elegant with http Response code, when accesing backend

### ISSUE THREAD

**Issue by gorzala** [dancier/show-dancer#5]
Accessing the profile-endpoint via a GET eg could lead to the following response codes:

1. 200 everyhting is fine, render what you get
2. 401 (unautenticaed), redirect to login
3. 404 (not found), tell the user to enter the profil information

We will often have something like this.
Investigate, how to cope with this situation in an elegant way, 

Definition of Elegant:

 - Without using if then else too much.
 - Extendable, new status with handling can be added easily with good readability

Acceptance Criteria:
 - Investigation's result is linked or described in this ticket
 - If necessary, a follow up ticket is created for future steps.

----
Check this:
https://jaxenter.de/angular-http-interceptoren-63488
and this:
https://stackoverflow.com/questions/56663931/how-to-make-angular-response-to-http-401

**Comment by Qwby** [comment]
One way of doing this is Interceptors, as you mentioned. Another way, when handling things with interceptors alone is not enough, is [wrapping the default http client in a custom HttpClient](https://dev.to/faisalejaz/angular-interceptor-a-better-alternative-166n) which is something I have seen being used in bigger projects with more complicated logic surrounding http calls from the frontend.

That having said, if we want to keep the 200/404 logic in the backend, I think we can do the current requirements the following way:
- have the profile page tell the ProfileService to get the profile, if there is a 404 render or redirect to the "edit profile" view, otherwise render or redirect to the "view profile of current user" view. This logic can just be part of a service or a component.
- Handle the 401-situation in an interceptor first, since this will be a general thing for all requests going to the backend

If we at some point want a custom http client, we can add it later. What do you think?

**Comment by gorzala** [comment]
That sounds perfect. Let's start with your plan!
(the custom HTTP client approach something we have at work with dropwizard too ;-))

**Comment by gorzala** [comment]
(are you writing a ticket yourself?)

**Comment by Qwby** [comment]
yes

**Comment by halbekanne** [comment]
Ticket Closed for now, we know how to deal with it, either specific for a request or with an Interceptor for all requests.
